server:
  port: 8080

client-port:
  port: 1280

socket-server:
  host: 0.0.0.0
  port: 8086


spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            userPoolId: ap-southeast-2_BZmyVIE9e
            clientId: 4svd2bjk86mpci1eoj3m11rp4v
            clientSecret: 1h60tpfmk3k4kb7qunq9g9t02o9crbnjeurgbchmduv35ka7u88p
            region: ap-southeast-2
            scope:
              - email
              - openid
              - phone
            redirect-uri: http://localhost:5173/callback
        provider:
          cognito:
            jwk-set-uri: https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_BZmyVIE9e/.well-known/jwks.json
            token-uri: https://ap-southeast-2bzmyvie9e.auth.ap-southeast-2.amazoncognito.com/oauth2/token
            issuerUri: https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_BZmyVIE9e
            user-name-attribute: username